---
title: Codebook for FinalUCIDataset.txt
date: 2020-07-12 
author: Anna M
---

Data source:
This assignment uses the Human Activity Recognition Using Smartphones Data Set. The Human Activity Recognition database has been created built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors. More information on this data source can be found at http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones The specific copy of the dataset used for this assignment was downloaded from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip on 12/07/2020

Data feaures
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals include the following, which were selected for the assignment: 

mean(): Mean value
std(): Standard deviation

---------------------------------------------

Data preparation

The script which prepares the dataset is run_analysis.R

It makes use of the dplyr package and performs the following steps:

Load the dplyr package Download the zipfile for the assignment to a folder clled "UCI HAR Dataset" (creating the folder if it doesn't exist in the working directory)
Then unzip the download Load each of the 6 test and train datasets into R into a separate data frame Join the test and train datasets using rbind (concatenating by row), and set descriptive fieldnames 
    subjecttest and subjecttrain contain the ID of each data subject 
    ytest and ytrain contain the ID of each activity measured 
    features fieldnames are drawn from the second column of the reference table "features.txt" 
Use cbind to join the three dataframes together (by adding the extra columns) - subject, activity, features 
Identify fields which contain mean or standard deviation data and use these to create a list of fields for a subset, along with the subject and activity label columns Create a subset using these column or field names 
Obtain descriptive activity labels from the file “activity_labels.txt” and add them as a new column using merge 
Change the new activity column name from V2 and remove the old activitycode column 
Change the feature column names to be more descriptive 
Change acronyms and abbreviations to the full descriptive words 
Create a 2nd tidy dataset with the average of each variable for each activity and each subject
Output the data to a text file in the working directory


# Data report overview
The final dataset has the following dimensions:


---------------------------------
Feature                    Result
------------------------ --------
Number of observations        180

Number of variables            88
---------------------------------


# Codebook summary table

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Label   Variable                                                   Class         # unique  Missing  Description  
                                                                                   values                        
------- ---------------------------------------------------------- ----------- ---------- --------- -----------------------------------------------------------------------------------------------------
        **[subject]**                                              integer             30  0.00 %   Identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.          

        **[activity]**                                             character            6  0.00 %   The 6 activies performed (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)              
        
        **[timeBodyAccelerometer-mean()-X]**                       numeric            180  0.00 %   Mean time domain signals for Body Acceleration Measurement Windows in the X axial direction               

        **[timeBodyAccelerometer-mean()-Y]**                       numeric            180  0.00 %   Mean time domain signals for Body Acceleration Measurement Windows in the y axial direction             

        **[timeBodyAccelerometer-mean()-Z]**                       numeric            180  0.00 %   Mean time domain signals for Body Acceleration Measurement Windows in the z axial direction                

        **[timeGravityAccelerometer-mean()-X]**                    numeric            180  0.00 %   Mean time domain signals for Gravity Acceleration Measurement Windows in the x axial direction           

        **[timeGravityAccelerometer-mean()-Y]**                    numeric            180  0.00 %   Mean time domain signals for Gravity Acceleration Measurement Windows in the y axial direction                 

        **[timeGravityAccelerometer-mean()-Z]**                    numeric            180  0.00 %   Mean time domain signals for Gravity Acceleration Measurement Windows in the z axial direction                 

        **[timeBodyAccelerometerJerk-mean()-X]**                   numeric            180  0.00 %   Mean time domain signals for Body Jerk Acceleration Measurement Windows in the x axial direction                 

        **[timeBodyAccelerometerJerk-mean()-Y]**                   numeric            180  0.00 %   Mean time domain signals for Body Jerk Acceleration Measurement Windows in the y axial direction               

        **[timeBodyAccelerometerJerk-mean()-Z]**                   numeric            180  0.00 %   Mean time domain signals for Body Jerk Acceleration Measurement Windows in the z axial direction               

        **[timeBodyGyroscope-mean()-X]**                           numeric            180  0.00 %   Mean time domain signals for Body Gyroscope Measurement Windows in the x axial direction               

        **[timeBodyGyroscope-mean()-Y]**                           numeric            180  0.00 %   Mean time domain signals for Body Gyroscope Measurement Windows in the y axial direction                

        **[timeBodyGyroscope-mean()-Z]**                           numeric            180  0.00 %   Mean time domain signals for Body Gyroscope Measurement Windows in the z axial direction                

        **[timeBodyGyroscopeJerk-mean()-X]**                       numeric            180  0.00 %   Mean time domain signals for Body Jerk Gyroscope Measurement Windows in the x axial direction                

        **[timeBodyGyroscopeJerk-mean()-Y]**                       numeric            180  0.00 %   Mean time domain signals for Body Jerk Gyroscope Measurement Windows in the y axial direction                

        **[timeBodyGyroscopeJerk-mean()-Z]**                       numeric            180  0.00 %   Mean time domain signals for Body Jerk Gyroscope Measurement Windows in the z axial direction                  

        **[timeBodyAccelerometerMagnitude-mean()]**                numeric            180  0.00 %   Mean time domain signals for Body Acceleration Magnitude Measurement Windows                

        **[timeGravityAccelerometerMagnitude-mean()]**             numeric            180  0.00 %   Mean time domain signals for Gravity Acceleration Magnitude Measurement Windows              

        **[timeBodyAccelerometerJerkMagnitude-mean()]**            numeric            180  0.00 %   Mean time domain signals for Body Jerk Acceleration Magnitude Measurement Windows            

        **[timeBodyGyroscopeMagnitude-mean()]**                    numeric            180  0.00 %   Mean time domain signals for Body Gyroscope Magnitude Measurement Windows                

        **[timeBodyGyroscopeJerkMagnitude-mean()]**                numeric            180  0.00 %   Mean time domain signals for Body Gyroscope Jerk Magnitude Measurement Windows            

        **[frequencyBodyAccelerometer-mean()-X]**                  numeric            180  0.00 %   Frequency of Body Acceleration Measurement Windows in the X axial direction             

        **[frequencyBodyAccelerometer-mean()-Y]**                  numeric            180  0.00 %   Frequency of Body Acceleration Measurement Windows in the y axial direction                 

        **[frequencyBodyAccelerometer-mean()-Z]**                  numeric            180  0.00 %   Frequency of Body Acceleration Measurement Windows in the z axial direction               

        **[frequencyBodyAccelerometer-meanFreq()-X]**              numeric            180  0.00 %   mean frequency of Body Acceleration Measurement Windows in the x axial direction 

        **[frequencyBodyAccelerometer-meanFreq()-Y]**              numeric            180  0.00 %   mean frequency of Body Acceleration Measurement Windows in the y axial direction              

        **[frequencyBodyAccelerometer-meanFreq()-Z]**              numeric            180  0.00 %   mean frequency of Body Acceleration Measurement Windows in the z axial direction              

        **[frequencyBodyAccelerometerJerk-mean()-X]**              numeric            180  0.00 %   Frequency of Body Jerk Accelerometer Measurement Windows in the X axial direction             

        **[frequencyBodyAccelerometerJerk-mean()-Y]**              numeric            180  0.00 %   Frequency of Body Jerk Accelerometer Measurement Windows in the y axial direction              

        **[frequencyBodyAccelerometerJerk-mean()-Z]**              numeric            180  0.00 %   Frequency of Body Jerk Accelerometer Measurement Windows in the z axial direction              

        **[frequencyBodyAccelerometerJerk-meanFreq()-X]**          numeric            180  0.00 %   Mean frequency of Body Jerk Accelerometer Measurement Windows in the X axial direction              

        **[frequencyBodyAccelerometerJerk-meanFreq()-Y]**          numeric            180  0.00 %   Mean frequency of Body Jerk Accelerometer Measurement Windows in the y axial direction                

        **[frequencyBodyAccelerometerJerk-meanFreq()-Z]**          numeric            180  0.00 %   Mean frequency of Body Jerk Accelerometer Measurement Windows in the z axial direction                

        **[frequencyBodyGyroscope-mean()-X]**                      numeric            180  0.00 %   Frequency of Body Gyroscope Measurement Windows in the X axial direction              

        **[frequencyBodyGyroscope-mean()-Y]**                      numeric            180  0.00 %   Frequency of Body Gyroscope Measurement Windows in the y axial direction             

        **[frequencyBodyGyroscope-mean()-Z]**                      numeric            180  0.00 %   Frequency of Body Gyroscope Measurement Windows in the z axial direction             

        **[frequencyBodyGyroscope-meanFreq()-X]**                  numeric            180  0.00 %   Mean frequency of Body Gyroscope Measurement Windows in the X axial direction             

        **[frequencyBodyGyroscope-meanFreq()-Y]**                  numeric            180  0.00 %   Mean frequency of Body Gyroscope Measurement Windows in the y axial direction              

        **[frequencyBodyGyroscope-meanFreq()-Z]**                  numeric            180  0.00 %   Mean frequency of Body Gyroscope Measurement Windows in the z axial direction              

        **[frequencyBodyAccelerometerMagnitude-mean()]**           numeric            180  0.00 %   Frequency of Body Acellerometer Magnitude Windows 
        
        **[frequencyBodyAccelerometerMagnitude-meanFreq()]**       numeric            180  0.00 %   Mean frequency of Body Acellerometer Magnitude Windows              

        **[frequencyBodyAccelerometerJerkMagnitude-mean()]**       numeric            180  0.00 %   Frequency of Body Jerk Acellerometer Magnitude Windows              

        **[frequencyBodyAccelerometerJerkMagnitude-meanFreq()]**   numeric            180  0.00 %   Mean frequency of Body Acellerometer Magnitude Windows              

        **[frequencyBodyGyroscopeMagnitude-mean()]**               numeric            180  0.00 %   Frequency of Body Gyroscope Magnitude Windows              

        **[frequencyBodyGyroscopeMagnitude-meanFreq()]**           numeric            180  0.00 %   Mean frequency of Body Gyroscope Magnitude Windows              

        **[frequencyBodyGyroscopeJerkMagnitude-mean()]**           numeric            180  0.00 %   Frequency of Body Gyroscope Jerk Magnitude Windows              

        **[frequencyBodyGyroscopeJerkMagnitude-meanFreq()]**       numeric            180  0.00 %   Mean frequency of Body Gyroscope Magnitude Windows              

        **[angle(tBodyAccelerometerMean,gravity)]**                numeric            180  0.00 %   Angle of Body Accelerometer mean             

        **[angle(tBodyAccelerometerJerkMean),gravityMean)]**       numeric            180  0.00 %   Angle of Body Accelerometer mean             

        **[angle(tBodyGyroscopeMean,gravityMean)]**                numeric            180  0.00 %   Angle of Body Gyroscope mean            

        **[angle(tBodyGyroscopeJerkMean,gravityMean)]**            numeric            180  0.00 %   Angle of Body Jerk Gyroscope mean             

        **[angle(X,gravityMean)]**                                 numeric            180  0.00 %   Mean angle of X axial direction             

        **[angle(Y,gravityMean)]**                                 numeric            180  0.00 %   Mean angle of y axial direction                 

        **[angle(Z,gravityMean)]**                                 numeric            180  0.00 %   Mean angle of z axial direction                 

        **[timeBodyAccelerometer-std()-X]**                        numeric            180  0.00 %   Standard deviation of time domain signals for Body Acceleration Measurement Windows in the X axial direction             

        **[timeBodyAccelerometer-std()-Y]**                        numeric            180  0.00 %   Standard deviation of time domain signals for Body Acceleration Measurement Windows in the y axial direction                

        **[timeBodyAccelerometer-std()-Z]**                        numeric            180  0.00 %   Standard deviation of time domain signals for Body Acceleration Measurement Windows in the z axial direction                

        **[timeGravityAccelerometer-std()-X]**                     numeric            180  0.00 %   Standard deviation of time domain signals for Gravity Acceleration Measurement Windows in the X axial direction                

        **[timeGravityAccelerometer-std()-Y]**                     numeric            180  0.00 %   Standard deviation of time domain signals for Gravity Acceleration Measurement Windows in the y axial direction              

        **[timeGravityAccelerometer-std()-Z]**                     numeric            180  0.00 %   Standard deviation of time domain signals for Gravity Acceleration Measurement Windows in the z axial direction             

        **[timeBodyAccelerometerJerk-std()-X]**                    numeric            180  0.00 %   Standard deviation of time domain signals for Body Jerk Acceleration Measurement Windows in the X axial direction             

        **[timeBodyAccelerometerJerk-std()-Y]**                    numeric            180  0.00 %   Standard deviation of time domain signals for Body Jerk Acceleration Measurement Windows in the y axial direction               

        **[timeBodyAccelerometerJerk-std()-Z]**                    numeric            180  0.00 %   Standard deviation of time domain signals for Body Jerk Acceleration Measurement Windows in the z axial direction               

        **[timeBodyGyroscope-std()-X]**                            numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Measurement Windows in the X axial direction               

        **[timeBodyGyroscope-std()-Y]**                            numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Measurement Windows in the y axial direction               

        **[timeBodyGyroscope-std()-Z]**                            numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Measurement Windows in the z axial direction               

        **[timeBodyGyroscopeJerk-std()-X]**                        numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Jerk Measurement Windows in the X axial direction               

        **[timeBodyGyroscopeJerk-std()-Y]**                        numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Jerk Measurement Windows in the y axial direction  

        **[timeBodyGyroscopeJerk-std()-Z]**                        numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Jerk Measurement Windows in the z axial direction               

        **[timeBodyAccelerometerMagnitude-std()]**                 numeric            180  0.00 %   Standard deviation of time domain signals for Body Accelerometer Magnitude Measurement Windows              

        **[timeGravityAccelerometerMagnitude-std()]**              numeric            180  0.00 %   Standard deviation of time domain signals for Gravity Accelerometer Magnitude Measurement Windows            

        **[timeBodyAccelerometerJerkMagnitude-std()]**             numeric            180  0.00 %   Standard deviation of time domain signals for Body Jerk Accelerometer Magnitude Measurement Windows             

        **[timeBodyGyroscopeMagnitude-std()]**                     numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Magnitude Measurement Windows             

        **[timeBodyGyroscopeJerkMagnitude-std()]**                 numeric            180  0.00 %   Standard deviation of time domain signals for Body Gyroscope Jerk Magnitude Measurement Windows             

        **[frequencyBodyAccelerometer-std()-X]**                   numeric            180  0.00 %   Standard deviation of frequency of Body Acellerometer Windows in the X axial direction                

        **[frequencyBodyAccelerometer-std()-Y]**                   numeric            180  0.00 %   Standard deviation of frequency of Body Acellerometer Windows in the y axial direction             

        **[frequencyBodyAccelerometer-std()-Z]**                   numeric            180  0.00 %   Standard deviation of frequency of Body Acellerometer Windows in the z axial direction             

        **[frequencyBodyAccelerometerJerk-std()-X]**               numeric            180  0.00 %   Standard deviation of frequency of Body Acellerometer Jerk Windows in the X axial direction             

        **[frequencyBodyAccelerometerJerk-std()-Y]**               numeric            180  0.00 %   Standard deviation of frequency of Body Acellerometer Jerk Windows in the y axial direction             

        **[frequencyBodyAccelerometerJerk-std()-Z]**               numeric            180  0.00 %   Standard deviation of frequency of Body Acellerometer Jerk Windows in the z axial direction             

        **[frequencyBodyGyroscope-std()-X]**                       numeric            180  0.00 %   Standard deviation of frequency of Body Gyroscope Windows in the X axial direction             

        **[frequencyBodyGyroscope-std()-Y]**                       numeric            180  0.00 %   Standard deviation of frequency of Body Gyroscope Windows in the y axial direction             

        **[frequencyBodyGyroscope-std()-Z]**                       numeric            180  0.00 %   Standard deviation of frequency of Body Gyroscope Windows in the z axial direction             

        **[frequencyBodyAccelerometerMagnitude-std()]**            numeric            180  0.00 %   Standard deviation of frequency of Body Accelerometer Mangnitude Windows 

        **[frequencyBodyAccelerometerJerkMagnitude-std()]**        numeric            180  0.00 %   Standard deviation of frequency of Body Jerk Accelerometer Mangnitude Windows              

        **[frequencyBodyGyroscopeMagnitude-std()]**                numeric            180  0.00 %   Standard deviation of frequency of Body Gyroscope Mangnitude Windows              

        **[frequencyBodyGyroscopeJerkMagnitude-std()]**            numeric            180  0.00 %   Standard deviation of frequency of Body Gyroscope Jerk Mangnitude Windows              
-----------------------------------------------------------------------------------------------------------------








